```{r}
library(tidyverse)
library(readxl)
library(plotly)
library(patchwork)
source("ppvFunctions.R")
```

Code Ideas
https://shiny.rstudio.com/gallery/explore-panel-data.html

C:\Users\alackey\OneDrive - DOI\Desktop\NPS Internship\PPV Study Automation\TEST March Raw PPV Data.xlsx
```{r}
source("ppvFunctions.R")
sheet_one <- formatData(read_excel("C:/Users/alackey/OneDrive - DOI/Desktop/NPS Internship/PPV Study Automation/TEST December Raw PPV Data.xlsx", sheet = 1))
sheet_two <- formatData(read_excel("C:/Users/alackey/OneDrive - DOI/Desktop/NPS Internship/PPV Study Automation/TEST December Raw PPV Data.xlsx", sheet = 2))
```

```{r}

```

```{r}
# test_ranges <- data.frame(ranges = c("12-4", "5-6, 9", "7-8, 10-11"), names = c("Group 1", "Group 2", "Group 3"))
test_ranges <- data.frame(ranges = c("12-2", "3-7", "8", "9-11"), names = c("Winter", "Spr_Sum", "August", "Fall"))
# test_ranges <- data.frame(ranges = c("8, 12, 1, 2", "3-7, 9-11"), names = c("Off-Peak", "Peak"))
filt <- applyRanges(sheet_two, checkRange(test_ranges)$ranges)
```

```{r}
source("ppvFunctions.R")
poiReg(filt)$plot
```

```{r}

```

```{r}
a <- figRange(applyRanges(sheet_two, checkRange(test_ranges)$ranges_plot))
b <- customGP(filt, "monthNum", "group")
c <- customGP(filt, "monthNum", "entrance")
s1 <- (b | c) / c
s1
```